### ISSUE TITLE
Requêtes paginations

### ISSUE THREAD

**Issue by SoleneHirles** [Mitrano-sensei/APP5_API_Dungeon#5]

**Comment by Mitrano-sensei** [comment]
On peut faire des requêtes de la forme /players/{page}, ou alors /players/?page=1
TBD

**Comment by Baashen** [comment]
https://www.prisma.io/docs/orm/prisma-client/queries/pagination

**Comment by SoleneHirles** [comment]
pagesize=5

Page=2 renvoie les éléments du 6ème au 10ème

**Comment by SoleneHirles** [comment]
Done 

=> A merge

**Comment by SoleneHirles** [comment]
En Attente de score pour finir
